### PR TITLE
Maintenance 11 12 2020

### PR DESCRIPTION
**Pull request by andreysaksonov**

### CODE REVIEW

**Comment by enrique-alonso-martin-pw** [comment]
I think it failed to build because the urls for maven must use `https` now.

**Comment by enrique-alonso-martin-pw** [comment]
```
[ERROR] /home/travis/build/payworks/tcp-mocker/tcp-mocker-app/src/main/java/io/payworks/labs/[secure]/configuration/SwaggerConfiguration.java:[21,2] cannot find symbol

[ERROR]   symbol: class EnableSwagger2
```

**Comment by enrique-alonso-martin-pw** [comment]
Still failing because of swagger. Feel free to remove it if it is causing too much trouble

**Comment by andreysaksonov** [comment]
> Still failing because of swagger. Feel free to remove it if it is causing too much trouble

I rolled back version and created issue in backlog. Looks like 2.10+ of springfox contains breaking changes

**Review by enrique-alonso-martin-pw — APPROVED** [review]
Thank-Q!

**Pull request merged**
